<?
    define('CONFIG',[
        'jugadores'=>[
            'vegueta'=>[
                'nombre'=>'vegueta',
                'assets'=>[
                    'inicio'=>'resources/assets/vegueta1.png',
                    'juego'=>'resources/assets/veguetaentreno.gif',
                    'fin'=>'resources/assets/veguetacansado.gif',
                    'ganador'=>'resources/assets/veguetawin.gif',
                ],
            ],
            'goku'=>[
                'nombre'=>'goku',
                'assets'=>[
                    'inicio'=>'resources/assets/goku1.png',
                    'juego'=>'resources/assets/gokuentreno.gif',
                    'fin'=>'resources/assets/vs.gif',
                    'ganador'=>'resources/assets/gokuwin.gif',
                ],
            ]
            ],
        'TIME_RESTART'=>30,
    ]);
?>